import * as fs from "node:fs";
import * as path from "node:path";
// Note: we will dynamically import modules that touch storage AFTER setting USE_MEM_STORAGE
// so that we run entirely in memory and don't require a DB during synthetic generation.
import type { FeatureVector } from "./features.js";

/**
 * Generate a synthetic training CSV by:
 *  - Creating N synthetic users with Open Banking data generated by
 *    `SyntheticChileanProvider` — a per-user latent profile (ingreso, carga financiera,
 *    volatilidad de ingreso) calibrado contra estadísticas públicas de Chile (BCCh EFH
 *    2024 / CMF), no el `MockProvider` (que genera datos casi idénticos para todo
 *    usuario — ver syntheticChileanProvider.ts para el detalle del bug que esto corrige).
 *  - Computing the feature vector for each user
 *  - Generating a synthetic label deterministically from that same latent profile via
 *    `sampleLabel` (Bernoulli(trueDefaultProbability(profile))), no de `scorePD` aplicado
 *    sobre las features derivadas (que tiene pesos en cero para varias de ellas) ni de
 *    `Math.random()` puro.
 *  - Writing rows: [features..., label]
 *
 * Usage:
 *   tsx server/ml/make_synth_training.ts [outPath] [nUsers] [windowDays]
 *
 * Defaults:
 *   outPath    = server/ml/out/synth_features.csv
 *   nUsers     = 2000
 *   windowDays = 90
 */
async function main() {
  const outPath =
    process.argv[2] || path.join(process.cwd(), "server", "ml", "out", "synth_features.csv");
  const nUsers = process.argv[3] ? parseInt(process.argv[3], 10) : 2000;
  const windowDays = process.argv[4] ? parseInt(process.argv[4], 10) : 90;

  // Force memory storage for this script
  if (!process.env.USE_MEM_STORAGE) process.env.USE_MEM_STORAGE = "1";

  // Dynamic imports after setting env
  const { ingestOpenBankingForUser } = await import("../jobs/ingest.js");
  const { buildUserFeatureVector } = await import("./features.js");
  const { SyntheticChileanProvider, sampleProfile, sampleLabel } =
    await import("./syntheticChileanProvider.js");
  const { storage } = await import("../storage.js");

  await fs.promises.mkdir(path.dirname(outPath), { recursive: true });

  // Define feature columns explicitly to ensure stable order
  const cols: Array<keyof FeatureVector> = [
    "windowDays",
    "txCount",
    "debitCount",
    "creditCount",
    "totalDebits",
    "totalCredits",
    "avgAmount",
    "stdAmount",
    "activeDays",
    "debitCreditRatio",
    "incomeRegularity",
    "topCategoryShare",
    // new DTI & volatility features
    "monthlyIncome",
    "monthlyDebits",
    "dti",
    "dtiCapped",
    "incomeTrend30_90",
    "netCashflowVolatility",
    "recurringExpenseShare",
  ];

  const header = cols.join(",") + ",label\n";
  await fs.promises.writeFile(outPath, header, { encoding: "utf-8" });

  for (let i = 1; i <= nUsers; i++) {
    const userId = `synth-${i}`;
    try {
      // accounts.userId es FK a users.id — crear la fila de usuario antes de ingestar.
      await storage.createUser({
        id: userId,
        username: userId,
        email: `${userId}@synth.coda.local`,
        passwordHash: "synthetic-not-a-real-hash",
      });

      // Populate synthetic OB data for this user (heterogéneo por usuario, calibrado a Chile)
      await ingestOpenBankingForUser(userId, new SyntheticChileanProvider());

      // Compute features
      const fv = await buildUserFeatureVector(userId, windowDays);

      // Etiqueta derivada del mismo perfil latente que generó las transacciones
      const profile = sampleProfile(userId);
      const label = sampleLabel(userId, profile);

      const row = cols.map((c) => fv[c] as number).join(",") + "," + label + "\n";
      await fs.promises.appendFile(outPath, row, { encoding: "utf-8" });

      if (i % 25 === 0) {
        console.log(`Generated ${i}/${nUsers} synthetic users...`);
      }
    } catch (e) {
      console.error(`Failed for user ${userId}`, e);
    }
  }

  console.log(`Synthetic training data written to ${outPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
